name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.22'
        
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.3
      
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64
        
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release --verbose
        
    - name: Verify executable exists
      run: |
        if (Test-Path "build\Release\CursorTrail.exe") {
          Write-Host "Executable built successfully"
          Get-ChildItem "build\Release\CursorTrail.exe"
        } else {
          Write-Error "Executable not found!"
          exit 1
        }
        
    - name: Create artifact directory
      run: |
        mkdir artifacts
        copy build\Release\CursorTrail.exe artifacts\
        copy CursorTrail\cursortrail.png artifacts\
        copy CursorTrail\sprite.frag artifacts\
        copy CursorTrail\sprite.vs artifacts\
        echo "Built on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" > artifacts\BUILD_INFO.txt
        echo "Commit: ${{ github.sha }}" >> artifacts\BUILD_INFO.txt
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: cursor-trail-windows-x64
        path: artifacts/
        retention-days: 30
        
    - name: Upload release asset (if release)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: artifacts/CursorTrail.exe
        asset_name: CursorTrail-Windows-x64.exe
        asset_content_type: application/octet-stream